apiVersion: v1
kind: Pod
metadata:
  labels:
    run: wintcpclient
  name: wintcpclient
spec:
  nodeSelector:
    "kubernetes.io/os": windows
  containers:
  - image: stevegriffith/wintcptester:1809
    name: wintcptester
    command: [ "powershell.exe" ]
    args: [ "./dotnettcp-sender.exe wintcpserver.default.svc.cluster.local 8000" ]
  restartPolicy: Never