apiVersion: v1
kind: Service
metadata:
  name: wintcpserver
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: wintcpserver
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: wintcpserver
  name: wintcpserver
spec:
  nodeSelector:
    "kubernetes.io/os": windows
  containers:
  - image: stevegriffith/wintcptester:1809v2
    name: wintcptester
    command: [ "powershell.exe" ]
    args: [ "./dotnettcp.exe", "0.0.0.0", "8000" ]
    # The following does not work
    #args: [ "./dotnettcp.exe", "127.0.0.1", "8000" ]
    ports:
    - containerPort: 8000
  restartPolicy: Never